/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.oodt.cas.filemgr.repository;

import static dev.hegel.Generators.lists;
import static dev.hegel.Generators.sampledFrom;
import static dev.hegel.Generators.text;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import dev.hegel.Generator;
import dev.hegel.HegelTest;
import dev.hegel.TestCase;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.apache.oodt.cas.filemgr.HsqlTestDatabase;
import org.apache.oodt.cas.filemgr.structs.ProductType;

/**
 * Properties for {@link DataSourceRepositoryManager}, the database-backed
 * store of product type policy.
 *
 * <p>A product type is what tells the file manager where a product's bytes
 * are archived and which versioner names the file on the way in, so a type
 * that does not survive a round trip is an ingest that lands in the wrong
 * place — or not at all. The class has no unit tests and, like the rest of
 * the JDBC layer, builds its statements by concatenating caller data into SQL.
 *
 * <p>The schema mirrors {@code cas-filemgr-repositorymgr-schema-oracle.sql},
 * translated to HSQLDB with the identity column {@code addProductType} relies
 * on when it reads {@code MAX(product_type_id)} back.
 */
class DataSourceRepositoryManagerPropertyTest {

  private static final String SCHEMA_TYPES =
      "CREATE TABLE product_types ("
          + "product_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,"
          + "product_type_name varchar(255) NOT NULL,"
          + "product_type_description varchar(255),"
          + "product_type_repository_path varchar(255),"
          + "product_type_versioner_class varchar(255))";

  private static Generator<String> plainText() {
    return text().minSize(1).maxSize(8).categories("Lu", "Ll", "Nd");
  }

  private static HsqlTestDatabase freshRepositoryDb() throws Exception {
    HsqlTestDatabase db = HsqlTestDatabase.create("repomgr");
    try {
      db.execute(SCHEMA_TYPES);
    } catch (Exception e) {
      db.close();
      throw e;
    }
    return db;
  }

  private static ProductType type(String name, String description, String path, String versioner) {
    ProductType type = new ProductType();
    type.setName(name);
    type.setDescription(description);
    type.setProductRepositoryPath(path);
    type.setVersioner(versioner);
    return type;
  }

  /**
   * A product type that was added must come back unchanged, both by the id the
   * manager assigned to it and by its name.
   *
   * <p>The repository path is the archive root for every product of that type
   * and the versioner class decides the archived filename, so a field that
   * changes in transit misfiles data.
   */
  @HegelTest(testCases = 25)
  void addedProductTypeRoundTripsByIdAndByName(TestCase tc) throws Exception {
    String name = tc.draw(plainText(), "name");
    String description = tc.draw(plainText(), "description");
    String path = tc.draw(plainText(), "path");
    String versioner = tc.draw(plainText(), "versioner");

    HsqlTestDatabase db = freshRepositoryDb();
    try {
      DataSourceRepositoryManager repo = new DataSourceRepositoryManager(db.dataSource());
      ProductType added =
          type(name, description, "file:/archive/" + path, "org.example." + versioner);
      repo.addProductType(added);

      String id = added.getProductTypeId();
      assertNotNull(id, "addProductType did not assign an id");

      ProductType byId = repo.getProductTypeById(id);
      assertNotNull(byId, "product type " + id + " was not found by id");
      assertEquals(name, byId.getName());
      assertEquals(description, byId.getDescription());
      assertEquals(added.getProductRepositoryPath(), byId.getProductRepositoryPath());
      assertEquals(added.getVersioner(), byId.getVersioner());

      ProductType byName = repo.getProductTypeByName(name);
      assertNotNull(byName, "product type '" + name + "' was not found by name");
      assertEquals(id, byName.getProductTypeId(), "name lookup returned a different type");
    } finally {
      db.close();
    }
  }

  /**
   * A sequence of add, modify and remove commands must leave the repository
   * agreeing with an in-memory model of what those commands should have done,
   * checked after every step.
   *
   * <p>The model is a map from assigned id to the type's four fields. After
   * each command the property asks for every type it believes exists, for the
   * ones it believes were removed, and for the whole listing.
   */
  @HegelTest(testCases = 25)
  void repositoryAgreesWithAnInMemoryModel(TestCase tc) throws Exception {
    List<String> commands =
        tc.draw(
            lists(sampledFrom(List.of("add", "modify", "remove"))).minSize(1).maxSize(10),
            "commands");
    List<String> names = tc.draw(lists(plainText()).minSize(10).maxSize(10), "names");

    HsqlTestDatabase db = freshRepositoryDb();
    try {
      DataSourceRepositoryManager repo = new DataSourceRepositoryManager(db.dataSource());
      Map<String, String[]> model = new LinkedHashMap<String, String[]>();
      Set<String> removed = new LinkedHashSet<String>();

      for (int step = 0; step < commands.size(); step++) {
        String command = commands.get(step);
        List<String> live = List.copyOf(model.keySet());

        if ("add".equals(command) || live.isEmpty()) {
          String name = names.get(step) + "_" + step;
          ProductType t = type(name, "d" + step, "file:/archive/" + step, "org.example.V" + step);
          repo.addProductType(t);
          model.put(
              t.getProductTypeId(),
              new String[] {name, "d" + step, "file:/archive/" + step, "org.example.V" + step});
        } else {
          String id = live.get(step % live.size());
          if ("modify".equals(command)) {
            String name = names.get(step) + "_m" + step;
            ProductType t =
                type(name, "d" + step, "file:/archive/m" + step, "org.example.M" + step);
            t.setProductTypeId(id);
            repo.modifyProductType(t);
            model.put(
                id,
                new String[] {
                  name, "d" + step, "file:/archive/m" + step, "org.example.M" + step
                });
          } else {
            ProductType t = new ProductType();
            t.setProductTypeId(id);
            repo.removeProductType(t);
            model.remove(id);
            removed.add(id);
          }
        }

        tc.note("step " + step + " (" + command + ") -> model " + model.keySet());

        for (Map.Entry<String, String[]> entry : model.entrySet()) {
          ProductType got = repo.getProductTypeById(entry.getKey());
          assertNotNull(got, "step " + step + ": type " + entry.getKey() + " went missing");
          assertEquals(entry.getValue()[0], got.getName(), "step " + step + ": wrong name");
          assertEquals(
              entry.getValue()[1], got.getDescription(), "step " + step + ": wrong description");
          assertEquals(
              entry.getValue()[2],
              got.getProductRepositoryPath(),
              "step " + step + ": wrong repository path");
          assertEquals(
              entry.getValue()[3], got.getVersioner(), "step " + step + ": wrong versioner");
        }

        for (String gone : removed) {
          assertNull(
              repo.getProductTypeById(gone),
              "step " + step + ": removed type " + gone + " is still readable");
        }

        List<ProductType> listed = repo.getProductTypes();
        Set<String> listedIds = new LinkedHashSet<String>();
        if (listed != null) {
          for (ProductType t : listed) {
            listedIds.add(t.getProductTypeId());
          }
        }
        assertEquals(model.keySet(), listedIds, "step " + step + ": getProductTypes disagrees");
      }
    } finally {
      db.close();
    }
  }

  /**
   * A product type whose description contains an apostrophe must round trip.
   *
   * <p>A description is free text written by a human — "the instrument's
   * level 1 products" — and neither {@code ProductType} nor the repository
   * manager offers the caller anywhere to escape one.
   */
  @HegelTest(testCases = 25)
  void productTypeDescriptionContainingAnApostropheRoundTrips(TestCase tc) throws Exception {
    String description =
        tc.draw(text().minSize(1).maxSize(6).categories("Ll").includeCharacters("'"), "description");
    tc.assume(description.contains("'"));

    HsqlTestDatabase db = freshRepositoryDb();
    try {
      DataSourceRepositoryManager repo = new DataSourceRepositoryManager(db.dataSource());
      ProductType added = type("TheType", description, "file:/archive", "org.example.V");
      repo.addProductType(added);

      ProductType back = repo.getProductTypeById(added.getProductTypeId());
      assertNotNull(back, "the type could not be read back");
      assertEquals(description, back.getDescription(), "the description changed in transit");
    } finally {
      db.close();
    }
  }
}
