/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.oodt.cas.filemgr.catalog;

import static dev.hegel.Generators.integers;
import static dev.hegel.Generators.lists;
import static dev.hegel.Generators.sampledFrom;
import static dev.hegel.Generators.text;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import dev.hegel.Generator;
import dev.hegel.HegelTest;
import dev.hegel.TestCase;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.apache.oodt.cas.filemgr.HsqlTestDatabase;
import org.apache.oodt.cas.filemgr.structs.Product;
import org.apache.oodt.cas.filemgr.structs.ProductPage;
import org.apache.oodt.cas.filemgr.structs.ProductType;
import org.apache.oodt.cas.filemgr.structs.Query;
import org.apache.oodt.cas.filemgr.structs.Reference;
import org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException;
import org.apache.oodt.cas.metadata.Metadata;

/**
 * Properties of the parts of {@link ScienceDataCatalog} the existing
 * {@code ScienceDataCatalogPropertyTest} does not reach: the top-N listings,
 * the metadata projections, the backwards pager, the commit helper, and what
 * the class does when it is asked for something that is not there.
 *
 * <p>The catalog splits cleanly in two. Its read side is written in plain SQL
 * and runs on anything; its write side — {@code addMetadata},
 * {@code createGranule}, {@code createParameter} and the {@code dataPoint}
 * inserts they build — quotes every identifier in MySQL backticks, which no
 * other database will parse. That half is therefore stated here as what it
 * is: a caller on a standard-SQL database is told the write failed rather
 * than left to believe it succeeded. Everything else is about the read side.
 *
 * <p>Granules are seeded into the tables directly, as the existing suite does,
 * because {@code addProduct} is a stub and granules reach a real deployment's
 * database by other means.
 */
class ScienceDataCatalogReadPropertyTest {

  private static final String SCHEMA_DATASET =
      "CREATE TABLE dataset ("
          + "dataset_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,"
          + "longName varchar(120), shortName varchar(60), description varchar(255),"
          + "source varchar(255), referenceURL varchar(255))";

  private static final String SCHEMA_GRANULE =
      "CREATE TABLE granule ("
          + "granule_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,"
          + "dataset_id INTEGER, filename varchar(255) NOT NULL)";

  private static Generator<String> plainText() {
    return text().minSize(1).maxSize(8).categories("Lu", "Ll", "Nd");
  }

  private static HsqlTestDatabase freshScienceDb() throws Exception {
    HsqlTestDatabase db = HsqlTestDatabase.create("scienceread");
    try {
      db.executeAll(SCHEMA_DATASET, SCHEMA_GRANULE);
    } catch (Exception e) {
      db.close();
      throw e;
    }
    return db;
  }

  private static void seedDataset(HsqlTestDatabase db, int id, String shortName)
      throws Exception {
    db.execute(
        "INSERT INTO dataset (dataset_id, longName, shortName, description, source, referenceURL) "
            + "VALUES (" + id + ", '" + shortName + " long', '" + shortName
            + "', 'seeded', 'test', 'http://example.invalid')");
  }

  private static void seedGranule(HsqlTestDatabase db, int id, int datasetId,
      String filename) throws Exception {
    db.execute("INSERT INTO granule (granule_id, dataset_id, filename) VALUES ("
        + id + ", " + datasetId + ", '" + filename + "')");
  }

  private static ProductType dataset(int id, String shortName) {
    ProductType type = new ProductType();
    type.setProductTypeId(String.valueOf(id));
    type.setName(shortName);
    return type;
  }

  private static ScienceDataCatalog catalog(HsqlTestDatabase db, int pageSize) {
    return new ScienceDataCatalog(db.dataSource(), null, pageSize);
  }

  private static List<String> idsInOrder(List<Product> products) {
    List<String> ids = new ArrayList<String>();
    if (products != null) {
      for (Product p : products) {
        ids.add(p.getProductId());
      }
    }
    return ids;
  }

  /**
   * {@code getTopNProducts} must return the {@code n} highest-numbered
   * granules, newest first.
   *
   * <p>Granule identifiers ascend as granules arrive, so "the top N" is "the N
   * most recently ingested", which is what a monitoring page shows. Asking for
   * more than exist must give everything rather than failing.
   */
  @HegelTest(testCases = 20)
  void topNReturnsTheHighestNumberedGranulesNewestFirst(TestCase tc)
      throws Exception {
    int count = tc.draw(integers().min(1).max(8), "count");
    int n = tc.draw(integers().min(1).max(10), "n");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, "AIRS");
      for (int i = 1; i <= count; i++) {
        seedGranule(db, i, 1, "a" + i + ".nc");
      }

      List<Product> top = cat.getTopNProducts(n);
      assertNotNull(top, "getTopNProducts returned nothing at all");

      List<String> expected = new ArrayList<String>();
      for (int i = count; i >= 1 && expected.size() < Math.min(n, count); i--) {
        expected.add(String.valueOf(i));
      }
      assertEquals(expected, idsInOrder(top),
          "getTopNProducts did not return the most recent granules newest "
              + "first");
    } finally {
      db.close();
    }
  }

  /**
   * {@code getTopNProducts} restricted to a dataset must return only that
   * dataset's granules.
   *
   * <p>A deployment holds every instrument's granules in one table. Listing
   * one instrument's newest files under another's is data attributed to the
   * wrong source.
   */
  @HegelTest(testCases = 20)
  void topNRestrictedToADatasetReturnsOnlyItsGranules(TestCase tc)
      throws Exception {
    int mine = tc.draw(integers().min(1).max(6), "mine");
    int others = tc.draw(integers().min(0).max(6), "others");
    int n = tc.draw(integers().min(1).max(8), "n");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, "AIRS");
      seedDataset(db, 2, "MODIS");

      Set<String> mineIds = new LinkedHashSet<String>();
      int nextId = 1;
      for (int i = 0; i < mine; i++) {
        seedGranule(db, nextId, 1, "a" + nextId + ".nc");
        mineIds.add(String.valueOf(nextId));
        nextId++;
      }
      for (int i = 0; i < others; i++) {
        seedGranule(db, nextId, 2, "m" + nextId + ".nc");
        nextId++;
      }

      List<Product> top = cat.getTopNProducts(n, dataset(1, "AIRS"));
      assertNotNull(top, "getTopNProducts returned nothing for the dataset");
      assertEquals(Math.min(n, mine), top.size(),
          "getTopNProducts returned the wrong number of granules for the "
              + "dataset");
      for (Product p : top) {
        assertTrue(mineIds.contains(p.getProductId()),
            "granule " + p.getProductId() + " belongs to another dataset");
      }
    } finally {
      db.close();
    }
  }

  /**
   * The metadata this catalog reports for a granule must name that granule and
   * its dataset.
   *
   * <p>{@code getMetadata} is what a client is handed alongside every product,
   * and the file manager's own conventions give {@code Filename} and
   * {@code ProductType} particular meaning. The catalog synthesises them from
   * the product rather than reading them back, so this states that the
   * synthesis uses the product it was given.
   */
  @HegelTest(testCases = 20)
  void metadataNamesTheGranuleAndItsDataset(TestCase tc) throws Exception {
    String filename = tc.draw(plainText(), "filename");
    String shortName = tc.draw(plainText(), "shortName");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, shortName);
      seedGranule(db, 1, 1, filename + ".nc");

      Product product = cat.getProductById("1");
      assertNotNull(product, "the seeded granule could not be read back");
      product.getProductType().setName(shortName);

      Metadata met = cat.getMetadata(product);
      assertNotNull(met, "getMetadata returned nothing");
      assertEquals(filename + ".nc", met.getMetadata("Filename"),
          "the metadata does not name the granule it describes");
      assertEquals(shortName, met.getMetadata("ProductType"),
          "the metadata does not name the dataset the granule belongs to");
      assertNotNull(met.getMetadata("CAS.ProductReceivedTime"),
          "the metadata carries no received time");
    } finally {
      db.close();
    }
  }

  /**
   * {@code getReducedMetadata} must return the full metadata restricted to the
   * keys asked for.
   *
   * <p>A client fetching a page of granules asks for a handful of keys rather
   * than everything. A key it asked for that comes back empty is data lost.
   */
  @HegelTest(testCases = 20)
  void reducedMetadataIsTheFullMetadataRestrictedToTheKeysAsked(TestCase tc)
      throws Exception {
    String filename = tc.draw(plainText(), "filename");
    List<String> asked = tc.draw(
        lists(sampledFrom(List.of("Filename", "ProductType", "FileLocation")))
            .minSize(1).maxSize(3), "asked");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, "AIRS");
      seedGranule(db, 1, 1, filename + ".nc");

      Product product = cat.getProductById("1");
      product.getProductType().setName("AIRS");

      Metadata full = cat.getMetadata(product);
      Set<String> wanted = new LinkedHashSet<String>(asked);
      Metadata reduced =
          cat.getReducedMetadata(product, new ArrayList<String>(wanted));
      assertNotNull(reduced, "getReducedMetadata returned nothing");

      for (String key : wanted) {
        assertEquals(full.getAllMetadata(key), reduced.getAllMetadata(key),
            "the reduced metadata disagrees with the full metadata about "
                + key);
      }
      Set<String> extra = new LinkedHashSet<String>(reduced.getAllKeys());
      extra.removeAll(wanted);
      assertEquals(Set.of(), extra,
          "getReducedMetadata returned keys nobody asked for: " + extra);
    } finally {
      db.close();
    }
  }

  /**
   * Paging backwards from the last page must reach the same granules as paging
   * forwards from the first.
   *
   * <p>The catalog carries its own copy of the pager rather than sharing
   * {@link DataSourceCatalog}'s, so its backwards half can be wrong on its
   * own.
   */
  @HegelTest(testCases = 20)
  void pagingBackwardsReachesTheSameGranulesAsPagingForwards(TestCase tc)
      throws Exception {
    int count = tc.draw(integers().min(1).max(9), "count");
    int pageSize = tc.draw(integers().min(1).max(4), "pageSize");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, pageSize);
      seedDataset(db, 1, "AIRS");
      ProductType type = dataset(1, "AIRS");
      for (int i = 1; i <= count; i++) {
        seedGranule(db, i, 1, "a" + i + ".nc");
      }

      Set<String> forwards = new LinkedHashSet<String>();
      ProductPage page = cat.getFirstPage(type);
      for (int guard = 0; page != null && guard <= count + 2; guard++) {
        if (page.getPageProducts() == null || page.getPageProducts().isEmpty()) {
          break;
        }
        forwards.addAll(idsInOrder(page.getPageProducts()));
        if (page.isLastPage()) {
          break;
        }
        page = cat.getNextPage(type, page);
      }

      Set<String> backwards = new LinkedHashSet<String>();
      page = cat.getLastProductPage(type);
      for (int guard = 0; page != null && guard <= count + 2; guard++) {
        if (page.getPageProducts() == null || page.getPageProducts().isEmpty()) {
          break;
        }
        backwards.addAll(idsInOrder(page.getPageProducts()));
        if (page.isFirstPage()) {
          break;
        }
        ProductPage previous = cat.getPrevPage(type, page);
        assertNotNull(previous,
            "getPrevPage returned nothing before page " + page.getPageNum());
        assertEquals(page.getPageNum() - 1, previous.getPageNum(),
            "getPrevPage did not step back by one");
        page = previous;
      }

      assertEquals(forwards, backwards,
          "paging backwards reached a different set of granules than paging "
              + "forwards");
    } finally {
      db.close();
    }
  }

  /**
   * A dataset nobody has put granules in must answer every read with nothing,
   * without throwing.
   *
   * <p>A dataset is declared before its first granule arrives, and everything
   * reading it in that window lands here.
   */
  @HegelTest(testCases = 20)
  void anEmptyDatasetAnswersEveryReadWithNothing(TestCase tc) throws Exception {
    int pageSize = tc.draw(integers().min(1).max(6), "pageSize");
    String filename = tc.draw(plainText(), "filename");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, pageSize);
      seedDataset(db, 1, "AIRS");
      ProductType type = dataset(1, "AIRS");

      assertEquals(0, cat.getNumProducts(type),
          "an empty dataset counted granules");
      assertEquals(0, cat.getTopNProducts(pageSize).size(),
          "an empty database produced a top-N listing");
      assertEquals(0, cat.getTopNProducts(pageSize, type).size(),
          "an empty dataset produced a top-N listing");
      assertNull(cat.getProductByName(filename + ".nc"),
          "an empty database found a granule by name");

      ProductPage first = cat.getFirstPage(type);
      assertNotNull(first, "an empty dataset produced no first page at all");
      assertTrue(first.getPageProducts() == null
              || first.getPageProducts().isEmpty(),
          "an empty dataset produced a first page holding granules");
    } finally {
      db.close();
    }
  }

  /**
   * A granule identifier that names nothing must produce nothing.
   *
   * <p>A client holding an identifier for a granule that has since been
   * removed reaches this on every route it has.
   */
  @HegelTest(testCases = 20)
  void anUnknownGranuleIdentifierProducesNothing(TestCase tc) throws Exception {
    int present = tc.draw(integers().min(0).max(4), "present");
    int absentId = tc.draw(integers().min(1000).max(9999), "absentId");
    String absentName = tc.draw(plainText(), "absentName");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, "AIRS");
      for (int i = 1; i <= present; i++) {
        seedGranule(db, i, 1, "a" + i + ".nc");
      }

      assertNull(cat.getProductById(String.valueOf(absentId)),
          "an identifier that names nothing produced a granule");
      assertNull(cat.getProductByName(absentName + ".missing"),
          "a filename that names nothing produced a granule");
      assertEquals(0, cat.getNumProducts(dataset(99, "NoSuchDataset")),
          "a dataset that does not exist counted granules");
      assertTrue(cat.getProductsByProductType(dataset(99, "NoSuchDataset")).isEmpty(),
          "a dataset that does not exist listed granules");
    } finally {
      db.close();
    }
  }

  /**
   * {@code commitQuery} must apply the statement it is given and, when asked,
   * report the identifier the row landed under.
   *
   * <p>Every write this catalog performs goes through this one method: it is
   * where the transaction is opened, committed and rolled back. The statements
   * its own callers hand it are MySQL-specific, but the method itself is not,
   * and it is public, so what it promises is worth stating on its own.
   */
  @HegelTest(testCases = 20)
  void commitQueryAppliesTheStatementAndReportsTheNewIdentifier(TestCase tc)
      throws Exception {
    int inserts = tc.draw(integers().min(1).max(5), "inserts");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, "AIRS");

      for (int i = 1; i <= inserts; i++) {
        int reported = cat.commitQuery(
            new StringBuffer("INSERT INTO granule (dataset_id, filename) "
                + "VALUES (1, 'g" + i + ".nc')"),
            "SELECT MAX(granule_id) AS max_id FROM granule");
        assertEquals(i, reported,
            "commitQuery reported identifier " + reported + " for the "
                + i + "th row it inserted");
        assertNotNull(cat.getProductById(String.valueOf(reported)),
            "commitQuery reported an identifier nothing is filed under");
      }

      assertEquals(inserts, cat.getNumProducts(dataset(1, "AIRS")),
          "commitQuery did not commit every statement it accepted");
    } finally {
      db.close();
    }
  }

  /**
   * A statement {@code commitQuery} cannot apply must be reported to the
   * caller and must leave the database as it was.
   *
   * <p>Silently swallowing a failed insert would leave a granule that the
   * catalog believes exists and the database has never heard of. The method
   * rolls back and rethrows, and both halves matter.
   */
  @HegelTest(testCases = 20)
  void commitQueryRollsBackAndReportsAStatementItCannotApply(TestCase tc)
      throws Exception {
    int existing = tc.draw(integers().min(0).max(4), "existing");
    String garbage = tc.draw(plainText(), "garbage");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, "AIRS");
      for (int i = 1; i <= existing; i++) {
        seedGranule(db, i, 1, "a" + i + ".nc");
      }

      assertThrows(SQLException.class,
          () -> cat.commitQuery(
              new StringBuffer("INSERT INTO no_such_table_" + garbage
                  + " (a) VALUES (1)"), null),
          "commitQuery accepted a statement the database rejected");

      assertEquals(existing, cat.getNumProducts(dataset(1, "AIRS")),
          "a failed statement changed how many granules the catalog holds");
    } finally {
      db.close();
    }
  }

  /**
   * On a database that is not MySQL, the write path reports its failure rather
   * than pretending to have stored anything.
   *
   * <p>{@code addMetadata} builds every statement with MySQL's backtick
   * quoting — {@code INSERT INTO `dataPoint` (`granule_id`, ...)} — which no
   * other database parses, so this catalog cannot ingest anywhere else. That
   * is a real limitation of the class and not something a property can work
   * around; what a caller can rely on either way is being told. The property
   * therefore pins the one thing that is portable about the write path: it
   * fails loudly.
   */
  @HegelTest(testCases = 20)
  void theWritePathReportsItsFailureOnAStandardSqlDatabase(TestCase tc)
      throws Exception {
    String filename = tc.draw(plainText(), "filename");
    String parameter = tc.draw(text().minSize(1).maxSize(5).categories("Ll"),
        "parameter");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, "AIRS");

      Metadata met = new Metadata();
      met.addMetadata("dataset_id", "1");
      met.addMetadata("granule_filename", filename + ".nc");
      met.addMetadata("param_" + parameter, parameter);
      met.addMetadata("data_" + parameter, "1.0,2.0,3.0,20110101T00:00Z,4.0");

      Product product = new Product();
      product.setProductName(filename + ".nc");

      assertThrows(CatalogException.class, () -> cat.addMetadata(met, product),
          "the MySQL-only write path claimed to have stored a granule on a "
              + "database that cannot parse its statements");
      assertThrows(SQLException.class,
          () -> cat.createGranule(1, filename + ".nc"),
          "createGranule claimed to have created a granule on a database "
              + "that cannot parse its statements");

      assertEquals(0, cat.getNumProducts(dataset(1, "AIRS")),
          "a write that failed left a granule behind anyway");
    } finally {
      db.close();
    }
  }

  /**
   * The calls this catalog does not implement must do nothing rather than
   * pretend.
   *
   * <p>{@link ScienceDataCatalog} is a read-mostly view over a science data
   * model, and the file manager's {@code Catalog} interface asks for more than
   * that. A caller has to know which side of the line each call is on: these
   * neither store nor throw, so ingesting through this catalog silently does
   * nothing, and the property records that rather than leaving it to be
   * discovered in a deployment.
   */
  @HegelTest(testCases = 20)
  void theUnimplementedHalfOfTheInterfaceDoesNothing(TestCase tc)
      throws Exception {
    String filename = tc.draw(plainText(), "filename");
    int existing = tc.draw(integers().min(0).max(4), "existing");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, "AIRS");
      for (int i = 1; i <= existing; i++) {
        seedGranule(db, i, 1, "a" + i + ".nc");
      }

      Product product = new Product();
      product.setProductId("1");
      product.setProductName(filename + ".nc");
      product.setProductType(dataset(1, "AIRS"));
      Reference reference = new Reference();
      reference.setOrigReference("file:/orig/" + filename);
      reference.setDataStoreReference("file:/archive/" + filename);
      reference.setFileSize(1);
      product.setProductReferences(List.of(reference));

      cat.addProduct(product);
      cat.addProductReferences(product);
      cat.modifyProduct(product);
      cat.setProductTransferStatus(product);
      cat.removeMetadata(new Metadata(), product);
      cat.removeProduct(product);

      assertEquals(existing, cat.getNumProducts(dataset(1, "AIRS")),
          "one of the unimplemented calls changed what the catalog holds");
      assertTrue(cat.getProductReferences(product).isEmpty(),
          "the catalog reported references it never stores");
      assertNull(cat.query(new Query(), dataset(1, "AIRS")),
          "the catalog answered a query it does not implement");
      assertNull(cat.getValidationLayer(),
          "the catalog reported a validation layer it was not given");
    } finally {
      db.close();
    }
  }
}
