/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.oodt.cas.filemgr.catalog;

import static dev.hegel.Generators.integers;
import static dev.hegel.Generators.lists;
import static dev.hegel.Generators.text;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import dev.hegel.Generator;
import dev.hegel.HegelTest;
import dev.hegel.TestCase;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.apache.oodt.cas.filemgr.HsqlTestDatabase;
import org.apache.oodt.cas.filemgr.structs.Product;
import org.apache.oodt.cas.filemgr.structs.ProductPage;
import org.apache.oodt.cas.filemgr.structs.ProductType;

/**
 * Properties for {@link ScienceDataCatalog}, the catalog that presents a
 * science data model — datasets, granules, parameters, data points — through
 * the file manager's {@code Catalog} interface.
 *
 * <p>This catalog is read-mostly: {@code addProduct} is a stub, and granules
 * arrive in the database by other means, so the properties seed the
 * {@code dataset} and {@code granule} tables directly and then state what the
 * read side must say about them. A granule that exists must be findable by id
 * and by filename, must appear in the listing, must be counted, and must be
 * reachable by paging.
 *
 * <p>Only the dialect-neutral part of the class is exercised. Its write path
 * and its data-point queries are written in MySQL's backtick-quoted syntax,
 * which the HSQLDB on this module's classpath cannot parse; a failure there
 * would be a statement about the fixture, not about the code, so those
 * methods are left alone.
 */
class ScienceDataCatalogPropertyTest {

  private static final String SCHEMA_DATASET =
      "CREATE TABLE dataset ("
          + "dataset_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,"
          + "longName varchar(120), shortName varchar(60), description varchar(255),"
          + "source varchar(255), referenceURL varchar(255))";

  private static final String SCHEMA_GRANULE =
      "CREATE TABLE granule ("
          + "granule_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,"
          + "dataset_id INTEGER, filename varchar(255) NOT NULL)";

  private static Generator<String> plainText() {
    return text().minSize(1).maxSize(8).categories("Lu", "Ll", "Nd");
  }

  private static HsqlTestDatabase freshScienceDb() throws Exception {
    HsqlTestDatabase db = HsqlTestDatabase.create("sciencedata");
    try {
      db.executeAll(SCHEMA_DATASET, SCHEMA_GRANULE);
    } catch (Exception e) {
      db.close();
      throw e;
    }
    return db;
  }

  private static void seedDataset(HsqlTestDatabase db, int id, String shortName) throws Exception {
    db.execute(
        "INSERT INTO dataset (dataset_id, longName, shortName, description, source, referenceURL) "
            + "VALUES ("
            + id
            + ", '"
            + shortName
            + " long', '"
            + shortName
            + "', 'seeded', 'test', 'http://example.invalid')");
  }

  private static void seedGranule(HsqlTestDatabase db, int id, int datasetId, String filename)
      throws Exception {
    db.execute(
        "INSERT INTO granule (granule_id, dataset_id, filename) VALUES ("
            + id
            + ", "
            + datasetId
            + ", '"
            + filename
            + "')");
  }

  private static ProductType dataset(int id, String shortName) {
    ProductType type = new ProductType();
    type.setProductTypeId(String.valueOf(id));
    type.setName(shortName);
    return type;
  }

  private static ScienceDataCatalog catalog(HsqlTestDatabase db, int pageSize) {
    return new ScienceDataCatalog(db.dataSource(), null, pageSize);
  }

  /**
   * A granule in the database must be reachable both by its id and by its
   * filename, and the two routes must agree about which granule it is.
   *
   * <p>These are the two lookups every client of the catalog interface uses.
   */
  @HegelTest(testCases = 20)
  void granuleIsRetrievableByIdAndByFilename(TestCase tc) throws Exception {
    List<String> filenames = tc.draw(lists(plainText()).minSize(1).maxSize(6), "filenames");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, "AIRS");

      Map<String, String> idToName = new LinkedHashMap<String, String>();
      for (int i = 0; i < filenames.size(); i++) {
        String filename = filenames.get(i) + "_" + i + ".nc";
        seedGranule(db, i + 1, 1, filename);
        idToName.put(String.valueOf(i + 1), filename);
      }

      for (Map.Entry<String, String> entry : idToName.entrySet()) {
        Product byId = cat.getProductById(entry.getKey());
        assertNotNull(byId, "granule " + entry.getKey() + " was not found by id");
        assertEquals(entry.getValue(), byId.getProductName(), "the filename changed in transit");
        assertEquals("1", byId.getProductType().getProductTypeId(), "wrong dataset on the product");

        Product byName = cat.getProductByName(entry.getValue());
        assertNotNull(byName, "granule '" + entry.getValue() + "' was not found by filename");
        assertEquals(
            entry.getKey(), byName.getProductId(), "filename lookup found a different granule");
      }
    } finally {
      db.close();
    }
  }

  /**
   * {@code getProducts()} must list every granule in the database, across all
   * datasets, and {@code getProductsByProductType} must list exactly the
   * granules of the dataset it was asked about.
   *
   * <p>A granule attributed to the wrong dataset is a data point served under
   * the wrong instrument.
   */
  @HegelTest(testCases = 20)
  void listingsSeparateTheDatasetsCorrectly(TestCase tc) throws Exception {
    int inFirst = tc.draw(integers().min(0).max(6), "inFirst");
    int inSecond = tc.draw(integers().min(0).max(6), "inSecond");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, "AIRS");
      seedDataset(db, 2, "MODIS");

      Set<String> first = new LinkedHashSet<String>();
      Set<String> second = new LinkedHashSet<String>();
      int nextId = 1;
      for (int i = 0; i < inFirst; i++) {
        seedGranule(db, nextId, 1, "a" + nextId + ".nc");
        first.add(String.valueOf(nextId));
        nextId++;
      }
      for (int i = 0; i < inSecond; i++) {
        seedGranule(db, nextId, 2, "m" + nextId + ".nc");
        second.add(String.valueOf(nextId));
        nextId++;
      }

      Set<String> all = new LinkedHashSet<String>(first);
      all.addAll(second);
      assertEquals(all, idsOf(cat.getProducts()), "getProducts did not list every granule");
      assertEquals(
          first,
          idsOf(cat.getProductsByProductType(dataset(1, "AIRS"))),
          "the first dataset's granule list is wrong");
      assertEquals(
          second,
          idsOf(cat.getProductsByProductType(dataset(2, "MODIS"))),
          "the second dataset's granule list is wrong");
    } finally {
      db.close();
    }
  }

  /**
   * {@code getNumProducts} must count exactly the granules of the dataset
   * named, and nothing from any other dataset.
   *
   * <p>Unlike the listing calls, this one resolves the dataset by its short
   * name rather than its id, so it is a genuinely separate lookup path and can
   * disagree with them.
   */
  @HegelTest(testCases = 20)
  void numProductsCountsOnlyTheNamedDatasetsGranules(TestCase tc) throws Exception {
    int mine = tc.draw(integers().min(0).max(6), "mine");
    int others = tc.draw(integers().min(0).max(6), "others");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, 5);
      seedDataset(db, 1, "AIRS");
      seedDataset(db, 2, "MODIS");

      int nextId = 1;
      for (int i = 0; i < mine; i++) {
        seedGranule(db, nextId++, 1, "a" + nextId + ".nc");
      }
      for (int i = 0; i < others; i++) {
        seedGranule(db, nextId++, 2, "m" + nextId + ".nc");
      }

      assertEquals(mine, cat.getNumProducts(dataset(1, "AIRS")), "wrong count for the first dataset");
      assertEquals(
          others, cat.getNumProducts(dataset(2, "MODIS")), "wrong count for the second dataset");
    } finally {
      db.close();
    }
  }

  /**
   * Walking the pages of a dataset must visit each of its granules exactly
   * once, and no granule from another dataset.
   *
   * <p>This catalog carries its own copy of the paging code rather than
   * sharing the {@link DataSourceCatalog} implementation, so it can be wrong
   * independently.
   */
  @HegelTest(testCases = 20)
  void pagingVisitsEveryGranuleOfTheDatasetExactlyOnce(TestCase tc) throws Exception {
    int count = tc.draw(integers().min(0).max(11), "count");
    int pageSize = tc.draw(integers().min(1).max(4), "pageSize");
    int decoys = tc.draw(integers().min(0).max(4), "decoys");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, pageSize);
      seedDataset(db, 1, "AIRS");
      seedDataset(db, 2, "MODIS");
      ProductType type = dataset(1, "AIRS");

      Set<String> expected = new LinkedHashSet<String>();
      int nextId = 1;
      for (int i = 0; i < count; i++) {
        seedGranule(db, nextId, 1, "a" + nextId + ".nc");
        expected.add(String.valueOf(nextId));
        nextId++;
      }
      for (int i = 0; i < decoys; i++) {
        seedGranule(db, nextId, 2, "m" + nextId + ".nc");
        nextId++;
      }

      ProductPage page = cat.getFirstPage(type);
      assertNotNull(page, "getFirstPage returned null");

      Set<String> seen = new LinkedHashSet<String>();
      int pagesWalked = 0;
      int totalPages = page.getTotalPages();

      for (int guard = 0; guard <= count + 2; guard++) {
        if (page.getPageProducts() == null || page.getPageProducts().isEmpty()) {
          break;
        }
        pagesWalked++;
        assertTrue(
            page.getPageNum() >= 1 && page.getPageNum() <= totalPages,
            "page number " + page.getPageNum() + " is outside 1.." + totalPages);
        assertTrue(
            page.getPageProducts().size() <= pageSize,
            "page " + page.getPageNum() + " holds more than " + pageSize + " granules");
        for (Product p : page.getPageProducts()) {
          assertNotNull(p, "a page held a null product");
          assertTrue(
              seen.add(p.getProductId()),
              "granule " + p.getProductId() + " appeared on more than one page");
        }
        if (page.isLastPage()) {
          break;
        }
        ProductPage next = cat.getNextPage(type, page);
        assertNotNull(next, "getNextPage returned null after page " + page.getPageNum());
        assertEquals(page.getPageNum() + 1, next.getPageNum(), "getNextPage did not advance by one");
        page = next;
        if (guard == count + 2) {
          fail("paging did not terminate after " + guard + " pages");
        }
      }

      assertEquals(expected, seen, "the pages do not partition the dataset");
      if (count > 0) {
        assertEquals(totalPages, pagesWalked, "walked a different number of pages than reported");
      }
    } finally {
      db.close();
    }
  }

  /**
   * The last page reported must be the page a caller reaches by walking
   * forward, and must hold the same granules either way.
   */
  @HegelTest(testCases = 20)
  void lastPageAgreesWithTheForwardWalk(TestCase tc) throws Exception {
    int count = tc.draw(integers().min(1).max(11), "count");
    int pageSize = tc.draw(integers().min(1).max(4), "pageSize");

    HsqlTestDatabase db = freshScienceDb();
    try {
      ScienceDataCatalog cat = catalog(db, pageSize);
      seedDataset(db, 1, "AIRS");
      ProductType type = dataset(1, "AIRS");
      for (int i = 1; i <= count; i++) {
        seedGranule(db, i, 1, "a" + i + ".nc");
      }

      ProductPage walked = cat.getFirstPage(type);
      for (int guard = 0; guard <= count + 2 && !walked.isLastPage(); guard++) {
        walked = cat.getNextPage(type, walked);
      }

      ProductPage last = cat.getLastProductPage(type);
      assertNotNull(last, "getLastProductPage returned null");
      assertTrue(last.isLastPage(), "getLastProductPage returned a page that denies being last");
      assertEquals(
          walked.getPageNum(),
          last.getPageNum(),
          "the last page reached is not the last page reported");
      assertEquals(
          idsOf(walked.getPageProducts()),
          idsOf(last.getPageProducts()),
          "the last page holds different granules depending on how it was asked for");
    } finally {
      db.close();
    }
  }

  private static Set<String> idsOf(List<Product> products) {
    Set<String> ids = new LinkedHashSet<String>();
    if (products != null) {
      for (Product p : new ArrayList<Product>(products)) {
        if (p != null) {
          ids.add(p.getProductId());
        }
      }
    }
    return ids;
  }
}
