/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.oodt.cas.workflow;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicLong;
import javax.sql.DataSource;
import org.apache.oodt.commons.database.DatabaseConnectionBuilder;
import org.apache.oodt.commons.database.SqlScript;

/**
 * A throwaway HSQLDB database holding the workflow manager's schema, for the
 * property suites over the {@code DataSource}-backed repositories.
 *
 * <p>The schema and the seed rows are the ones the existing
 * {@code TestWorkflowDataSourceRepository} suite uses — {@code
 * src/test/resources/workflow.sql} — so a property and a hand-written test are
 * talking about the same database. That suite keeps its database in a file in
 * the system temp directory and hands the same one to every test; a property
 * runs its body dozens of times and each run has to start from the same place,
 * so this one lives in memory under a name of its own and is dropped when it
 * is closed.
 */
public final class HsqlWorkflowDatabase implements AutoCloseable {

  /** Distinguishes one in-memory database from the next within a JVM. */
  private static final AtomicLong SEQUENCE = new AtomicLong();

  private final DataSource dataSource;

  private HsqlWorkflowDatabase(DataSource dataSource) {
    this.dataSource = dataSource;
  }

  /**
   * A database holding the workflow schema and the seed rows in workflow.sql:
   * one workflow, two tasks, four conditions and one event.
   */
  public static HsqlWorkflowDatabase seeded() throws Exception {
    String url = "jdbc:hsqldb:mem:pbt" + SEQUENCE.incrementAndGet();
    DataSource ds = DatabaseConnectionBuilder.buildDataSource("sa", "",
        "org.hsqldb.jdbcDriver", url);
    SqlScript schema = new SqlScript("src/test/resources/workflow.sql", ds);
    schema.loadScript();
    schema.execute();
    Connection connection = ds.getConnection();
    try {
      connection.commit();
    } finally {
      connection.close();
    }
    return new HsqlWorkflowDatabase(ds);
  }

  /**
   * The same database, but with {@code workflow_instances} redefined so that
   * the database issues the instance identifier.
   *
   * <p>{@code DataSourceWorkflowInstanceRepository.addWorkflowInstance} writes
   * an INSERT that names every column except {@code workflow_instance_id} and
   * then reads {@code MAX(workflow_instance_id)} back to learn what the row
   * was filed under, which only works if the column has a default. Oracle gets
   * one from the trigger in {@code workflow_oracle_create_sequences.sql}; in
   * the generic DDL every other database is pointed at it is a plain {@code
   * int NOT NULL PRIMARY KEY}, so the INSERT is rejected outright and nothing
   * further about the repository can be stated.
   * {@code theShippedSchemaAcceptsAnInstance} states that as a
   * property of its own; every other property here runs against this variant,
   * so that the storing, updating, removing, counting and paging the class
   * does are exercised rather than blocked behind one broken INSERT.
   */
  public static HsqlWorkflowDatabase withGeneratedInstanceIds()
      throws Exception {
    HsqlWorkflowDatabase database = seeded();
    Connection connection = database.dataSource.getConnection();
    try {
      Statement statement = connection.createStatement();
      try {
        statement.execute("DROP TABLE workflow_instances IF EXISTS");
        statement.execute("CREATE TABLE workflow_instances "
            + "(workflow_instance_id INTEGER GENERATED BY DEFAULT AS IDENTITY "
            + "PRIMARY KEY, "
            + "workflow_instance_status varchar(255), "
            + "workflow_id int NOT NULL, "
            + "current_task_id int NOT NULL, "
            + "start_date_time varchar(255), "
            + "end_date_time varchar(255), "
            + "current_task_start_date_time varchar(255), "
            + "current_task_end_date_time varchar(255), "
            + "priority float NOT NULL, "
            + "times_blocked int DEFAULT 0)");
      } finally {
        statement.close();
      }
    } finally {
      connection.close();
    }
    return database;
  }

  public DataSource dataSource() {
    return dataSource;
  }

  /**
   * Drops the database. An in-memory HSQLDB outlives the last connection to
   * it, so without this every property run would leave one behind for the rest
   * of the build.
   */
  @Override
  public void close() {
    try {
      Connection connection = dataSource.getConnection();
      try {
        Statement statement = connection.createStatement();
        try {
          statement.execute("SHUTDOWN");
        } finally {
          statement.close();
        }
      } finally {
        connection.close();
      }
    } catch (SQLException ignore) {
      // Nothing useful is left to do with a database being thrown away.
    }
    if (dataSource instanceof AutoCloseable) {
      try {
        ((AutoCloseable) dataSource).close();
      } catch (Exception ignore) {
        // As above.
      }
    }
  }
}
