-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements.  See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to You under the Apache License, Version 2.0
-- (the "License"); you may not use this file except in compliance with
-- the License.  You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- Schema for the ScienceDataCatalog.
--
-- This was MySQL and nothing else: backtick-quoted identifiers, int(10)
-- unsigned, auto_increment, ENGINE=MyISAM, DEFAULT CHARSET=latin1, and
-- AUTO_INCREMENT counters left at whatever they had reached in the database
-- this file was dumped from. None of that is SQL any other engine accepts,
-- so the catalog could not be created anywhere but MySQL -- which made the
-- MySQL dialect in its write path a symptom rather than the disease.
--
-- This is the standard-SQL form, verified against HSQLDB and written to the
-- same identity-column syntax the file manager's own test schema uses. The
-- MySQL original is kept alongside as sdschema-mysql.sql; run that one if
-- that is your database.
--
-- The identifiers are unquoted throughout, so every engine folds them the
-- same way it folds the ones in the queries. Quoting them would make them
-- case-sensitive and force the same quoting style into the Java, which is
-- how this started.

CREATE TABLE dataset (
  dataset_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  longName VARCHAR(120),
  shortName VARCHAR(60),
  description VARCHAR(4000),
  source VARCHAR(255),
  referenceURL VARCHAR(255)
);

CREATE TABLE granule (
  granule_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  dataset_id INTEGER,
  filename VARCHAR(255) NOT NULL
);

CREATE INDEX granule_dataset_id ON granule (dataset_id);

-- 'database' was NOT NULL with no default, and createParameter has never
-- written it -- MySQL outside strict mode quietly substituted an empty
-- string, and any engine that follows the standard would have rejected the
-- insert. Nullable, because nothing supplies it.
CREATE TABLE parameter (
  parameter_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  longName VARCHAR(120),
  shortName VARCHAR(60),
  description VARCHAR(4000),
  referenceURL VARCHAR(255),
  cellMethod VARCHAR(4000),
  missingDataFlag DOUBLE,
  units VARCHAR(60),
  verticalUnits VARCHAR(120),
  database VARCHAR(80),
  dataset_id INTEGER NOT NULL
);

CREATE TABLE dpMap (
  dataset_id INTEGER NOT NULL,
  parameter_id INTEGER NOT NULL,
  PRIMARY KEY (dataset_id, parameter_id)
);

CREATE TABLE dataPoint (
  dataPoint_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  granule_id INTEGER NOT NULL,
  dataset_id INTEGER NOT NULL,
  parameter_id INTEGER NOT NULL,
  time TIMESTAMP,
  latitude DOUBLE,
  longitude DOUBLE,
  vertical DOUBLE,
  value DOUBLE
);

CREATE INDEX dataPoint_granule_id ON dataPoint (granule_id);
