DROP TABLE product_type_element_map IF EXISTS;
DROP TABLE elements IF EXISTS;

CREATE TABLE elements (
  element_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  element_name varchar(255) NOT NULL,
  data_type_id int DEFAULT 0,
  dc_element varchar(100),
  element_description varchar(255)
);

CREATE TABLE product_type_element_map (
  product_type_element_map_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  product_type_id varchar(255) NOT NULL,
  element_id int NOT NULL
);

INSERT INTO elements (element_id, element_name, dc_element, element_description) VALUES (1, 'Filename', 'title', 'The file name');
INSERT INTO product_type_element_map (product_type_id, element_id) VALUES ('urn:oodt:GenericFile', 1);
