/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.oodt.cas.workflow.instrepo;

import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

import javax.sql.DataSource;

import junit.framework.TestCase;

import org.apache.oodt.cas.metadata.Metadata;
import org.apache.oodt.cas.workflow.structs.Workflow;
import org.apache.oodt.cas.workflow.structs.WorkflowInstance;
import org.apache.oodt.cas.workflow.structs.WorkflowTask;
import org.apache.oodt.commons.database.DatabaseConnectionBuilder;

/**
 * An instance update has to be one change, not forty two.
 *
 * <p>
 * Updating an instance committed the row, then deleted its metadata in a
 * transaction of its own, then inserted the metadata back one value at a time
 * with a commit for each. An instance with forty keys was forty two
 * transactions, and for the whole of that time a reader saw the instance with
 * some or none of its metadata.
 * </p>
 *
 * <p>
 * Readers notice. The services layer asks for every instance and filters them
 * in Java, dropping any whose state it cannot resolve rather than showing it, so
 * a running stage blinked out of the Executing page about once every fifteen
 * seconds -- measured at 17:08:36, :55, 17:09:06 and :25 on a 458 instance run.
 * That page is how you find out whether the stage is moving.
 * </p>
 */
public class TestInstanceUpdateIsAtomic extends TestCase {

  private static final int KEYS = 40;

  private String url;

  @Override
  protected void setUp() throws Exception {
    super.setUp();
    File dir = Files.createTempDirectory("winstdb-atomic").toFile();
    this.url = "jdbc:hsqldb:file:" + new File(dir, "winst").getAbsolutePath();
    Connection c = connect();
    Statement s = c.createStatement();
    s.execute("CREATE TABLE workflow_instances ("
        + "workflow_instance_id INTEGER GENERATED BY DEFAULT AS IDENTITY"
        + " (START WITH 1) PRIMARY KEY,"
        + "workflow_instance_status varchar(255), workflow_id varchar(255),"
        + "current_task_id varchar(255), start_date_time varchar(255),"
        + "end_date_time varchar(255), current_task_start_date_time varchar(255),"
        + "current_task_end_date_time varchar(255), priority float,"
        + "times_blocked int DEFAULT 0, waiting_on varchar(255) DEFAULT NULL)");
    s.execute("CREATE TABLE workflow_instance_metadata ("
        + "workflow_instance_id varchar(255), workflow_met_key varchar(255),"
        + "workflow_met_val varchar(255))");
    s.execute("SHUTDOWN");
    c.close();
  }

  /**
   * The defect, at the point it is visible: a reader must never see the
   * instance with part of its metadata missing.
   */
  public void testAReaderNeverSeesAHalfUpdatedInstance() throws Exception {
    final DataSourceWorkflowInstanceRepository writer = repository();
    WorkflowInstance inst = instance();
    writer.addWorkflowInstance(inst);
    final String id = inst.getId();

    final DataSourceWorkflowInstanceRepository reader = repository();
    final AtomicInteger shortReads = new AtomicInteger();
    final AtomicInteger reads = new AtomicInteger();
    final AtomicBoolean stop = new AtomicBoolean(false);

    Thread readerThread = new Thread(new Runnable() {
      public void run() {
        while (!stop.get()) {
          try {
            WorkflowInstance seen = find(reader.getWorkflowInstances(), id);
            if (seen != null) {
              reads.incrementAndGet();
              Metadata met = seen.getSharedContext();
              int keys = met == null ? 0 : met.getMap().keySet().size();
              if (keys != KEYS) {
                shortReads.incrementAndGet();
              }
            }
          } catch (Exception ignored) {
          }
        }
      }
    });
    readerThread.start();

    for (int i = 0; i < 40; i++) {
      inst.setStatus(i % 2 == 0 ? "Executing" : "Queued");
      writer.updateWorkflowInstance(inst);
    }
    stop.set(true);
    readerThread.join();

    assertTrue("the reader never saw the instance at all", reads.get() > 0);
    assertEquals("a reader saw the instance with the wrong number of metadata "
        + "keys " + shortReads.get() + " times out of " + reads.get()
        + " reads; an update must be one change, not one per value",
        0, shortReads.get());
  }

  /** And the update still actually updates. */
  public void testTheUpdateIsApplied() throws Exception {
    DataSourceWorkflowInstanceRepository repo = repository();
    WorkflowInstance inst = instance();
    repo.addWorkflowInstance(inst);
    String id = inst.getId();

    inst.setStatus("Executing");
    inst.getSharedContext().replaceMetadata("ProcessingNode", "spaghetti");
    repo.updateWorkflowInstance(inst);
    repo.release();

    WorkflowInstance back = find(repository().getWorkflowInstances(), id);
    assertNotNull(back);
    assertEquals("Executing", back.getStatus());
    assertEquals("spaghetti",
        back.getSharedContext().getMetadata("ProcessingNode"));
    assertEquals("every key survives the round trip, plus the one just added",
        KEYS + 1, back.getSharedContext().getMap().keySet().size());
  }

  /** Removing a key removes it, rather than leaving the old row behind. */
  public void testAKeyThatGoesAwayIsGone() throws Exception {
    DataSourceWorkflowInstanceRepository repo = repository();
    WorkflowInstance inst = instance();
    repo.addWorkflowInstance(inst);
    String id = inst.getId();

    inst.getSharedContext().removeMetadata("key-00");
    repo.updateWorkflowInstance(inst);
    repo.release();

    WorkflowInstance back = find(repository().getWorkflowInstances(), id);
    assertNotNull(back);
    assertNull("the delete has to still happen",
        back.getSharedContext().getMetadata("key-00"));
    assertEquals(KEYS - 1, back.getSharedContext().getMap().keySet().size());
  }

  /** An instance with no metadata at all is not an error. */
  public void testAnInstanceWithNoMetadataUpdatesCleanly() throws Exception {
    DataSourceWorkflowInstanceRepository repo = repository();
    WorkflowInstance inst = instance();
    inst.setSharedContext(new Metadata());
    repo.addWorkflowInstance(inst);
    String id = inst.getId();

    inst.setStatus("Executing");
    repo.updateWorkflowInstance(inst);
    repo.release();

    WorkflowInstance back = find(repository().getWorkflowInstances(), id);
    assertNotNull(back);
    assertEquals("Executing", back.getStatus());
  }

  // ----------------------------------------------------------- helpers ---

  private WorkflowInstance find(List<?> instances, String id) {
    for (Object o : instances) {
      WorkflowInstance inst = (WorkflowInstance) o;
      if (id.equals(inst.getId())) {
        return inst;
      }
    }
    return null;
  }

  private WorkflowInstance instance() {
    WorkflowInstance inst = new WorkflowInstance();
    Workflow workflow = new Workflow();
    workflow.setId("urn:oodt:w");
    WorkflowTask task = new WorkflowTask();
    task.setTaskId("urn:oodt:t");
    workflow.getTasks().add(task);
    inst.setWorkflow(workflow);
    inst.setCurrentTaskId("urn:oodt:t");
    inst.setStatus("Queued");
    Metadata met = new Metadata();
    for (int i = 0; i < KEYS; i++) {
      met.addMetadata(String.format("key-%02d", i), "value-" + i);
    }
    inst.setSharedContext(met);
    return inst;
  }

  private DataSourceWorkflowInstanceRepository repository() {
    DataSource ds = DatabaseConnectionBuilder.buildDataSource("sa", "",
        "org.hsqldb.jdbc.JDBCDriver", url);
    return new DataSourceWorkflowInstanceRepository(ds, true, 20);
  }

  private Connection connect() throws Exception {
    Class.forName("org.hsqldb.jdbc.JDBCDriver");
    return DriverManager.getConnection(url, "sa", "");
  }
}
