/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.oodt.cas.workflow.instrepo;

import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import javax.sql.DataSource;

import junit.framework.TestCase;

import org.apache.commons.dbcp2.ConnectionFactory;
import org.apache.commons.dbcp2.DriverManagerConnectionFactory;
import org.apache.commons.dbcp2.PoolableConnection;
import org.apache.commons.dbcp2.PoolableConnectionFactory;
import org.apache.commons.dbcp2.PoolingDataSource;
import org.apache.commons.pool2.impl.GenericObjectPool;
import org.apache.oodt.cas.metadata.Metadata;
import org.apache.oodt.cas.workflow.structs.Workflow;
import org.apache.oodt.cas.workflow.structs.WorkflowInstance;
import org.apache.oodt.cas.workflow.structs.WorkflowTask;

/**
 * Reading instances must not need more than the one connection it holds.
 *
 * <p>
 * Reading an instance list used to take a fresh connection for each
 * instance's metadata while still holding the one it was iterating, so a
 * pool with nothing left to give would park the reader forever. In the live
 * workflow manager that emptied the default eight-connection pool and, with
 * one of the waiting threads holding the repository's monitor, froze every
 * write behind it too. Pinning the pool to a single connection reproduces
 * that deterministically: if a read needs a second one, it never returns.
 * </p>
 */
public class TestInstanceReadsHoldOneConnection extends TestCase {

  private String url;

  @Override
  protected void setUp() throws Exception {
    super.setUp();
    File dir = Files.createTempDirectory("winstdb-onecx").toFile();
    this.url = "jdbc:hsqldb:file:" + new File(dir, "winst").getAbsolutePath();
    Class.forName("org.hsqldb.jdbc.JDBCDriver");
    Connection c = DriverManager.getConnection(url, "sa", "");
    Statement s = c.createStatement();
    s.execute("CREATE TABLE workflow_instances ("
        + "workflow_instance_id INTEGER GENERATED BY DEFAULT AS IDENTITY"
        + " (START WITH 1) PRIMARY KEY,"
        + "workflow_instance_status varchar(255), workflow_id varchar(255),"
        + "current_task_id varchar(255), start_date_time varchar(255),"
        + "end_date_time varchar(255), current_task_start_date_time varchar(255),"
        + "current_task_end_date_time varchar(255), priority float,"
        + "times_blocked int DEFAULT 0)");
    s.execute("CREATE TABLE workflow_instance_metadata ("
        + "workflow_instance_id varchar(255), workflow_met_key varchar(255),"
        + "workflow_met_val varchar(255))");
    s.execute("SHUTDOWN");
    c.close();
  }

  public void testAListReadNeedsOnlyTheConnectionItHolds() throws Exception {
    seed(3);
    final DataSourceWorkflowInstanceRepository repo = repository();
    List got = within(new Callable<List>() {
      public List call() throws Exception {
        return repo.getWorkflowInstances();
      }
    });
    assertEquals("all three instances should come back", 3, got.size());
    assertEquals("the metadata should come back with them", "drat",
        ((WorkflowInstance) got.get(0)).getSharedContext()
            .getMetadata("Source"));
  }

  public void testAStatusReadNeedsOnlyTheConnectionItHolds() throws Exception {
    seed(2);
    final DataSourceWorkflowInstanceRepository repo = repository();
    List got = within(new Callable<List>() {
      public List call() throws Exception {
        return repo.getWorkflowInstancesByStatus("Queued");
      }
    });
    assertEquals(2, got.size());
  }

  public void testASingleReadNeedsOnlyTheConnectionItHolds() throws Exception {
    final String id = seed(1);
    final DataSourceWorkflowInstanceRepository repo = repository();
    WorkflowInstance got = within(new Callable<WorkflowInstance>() {
      public WorkflowInstance call() throws Exception {
        return repo.getWorkflowInstanceById(id);
      }
    });
    assertNotNull(got);
    assertEquals("drat", got.getSharedContext().getMetadata("Source"));
  }

  /** Fails the test rather than hanging the build if a read parks. */
  private <T> T within(Callable<T> work) throws Exception {
    ExecutorService pool = Executors.newSingleThreadExecutor();
    try {
      Future<T> f = pool.submit(work);
      try {
        return f.get(20, TimeUnit.SECONDS);
      } catch (TimeoutException e) {
        f.cancel(true);
        fail("the read never returned -- it is waiting for a second "
            + "connection while holding the only one");
        return null;
      }
    } finally {
      pool.shutdownNow();
    }
  }

  private String seed(int count) throws Exception {
    // Seeded through a repository over an unbounded pool, so the constraint
    // under test applies only to the reads.
    DataSourceWorkflowInstanceRepository repo =
        new DataSourceWorkflowInstanceRepository(pooled(-1), true, 20);
    String last = null;
    for (int i = 0; i < count; i++) {
      WorkflowInstance inst = new WorkflowInstance();
      Workflow workflow = new Workflow();
      workflow.setId("urn:oodt:w");
      WorkflowTask task = new WorkflowTask();
      task.setTaskId("urn:oodt:t");
      workflow.getTasks().add(task);
      inst.setWorkflow(workflow);
      inst.setCurrentTaskId("urn:oodt:t");
      inst.setStatus("Queued");
      Metadata met = new Metadata();
      met.addMetadata("Source", "drat");
      inst.setSharedContext(met);
      repo.addWorkflowInstance(inst);
      last = inst.getId();
    }
    repo.release();
    return last;
  }

  private DataSourceWorkflowInstanceRepository repository() {
    return new DataSourceWorkflowInstanceRepository(pooled(1), true, 20);
  }

  private DataSource pooled(int maxTotal) {
    ConnectionFactory cf = new DriverManagerConnectionFactory(url, "sa", "");
    PoolableConnectionFactory pcf = new PoolableConnectionFactory(cf, null);
    pcf.setDefaultAutoCommit(true);
    pcf.setDefaultReadOnly(false);
    GenericObjectPool<PoolableConnection> pool =
        new GenericObjectPool<PoolableConnection>(pcf);
    pool.setMaxTotal(maxTotal);
    pcf.setPool(pool);
    return new PoolingDataSource<PoolableConnection>(pool);
  }
}
