/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.oodt.cas.workflow.instrepo;

import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.List;

import javax.sql.DataSource;

import junit.framework.TestCase;

import org.apache.oodt.cas.metadata.Metadata;
import org.apache.oodt.cas.workflow.structs.Workflow;
import org.apache.oodt.cas.workflow.structs.WorkflowInstance;
import org.apache.oodt.cas.workflow.structs.WorkflowTask;
import org.apache.oodt.commons.database.DatabaseConnectionBuilder;

/**
 * The reason an instance is waiting has to outlive the process that recorded
 * it -- that is the whole point of writing it down rather than inferring it,
 * and a restart is exactly when the question gets asked.
 */
public class TestWaitingOnPersistence extends TestCase {

  private String url;

  @Override
  protected void setUp() throws Exception {
    super.setUp();
    File dir = Files.createTempDirectory("winstdb-waiting").toFile();
    this.url = "jdbc:hsqldb:file:" + new File(dir, "winst").getAbsolutePath();
    Connection c = connect();
    Statement s = c.createStatement();
    s.execute("CREATE TABLE workflow_instances ("
        + "workflow_instance_id INTEGER GENERATED BY DEFAULT AS IDENTITY"
        + " (START WITH 1) PRIMARY KEY,"
        + "workflow_instance_status varchar(255), workflow_id varchar(255),"
        + "current_task_id varchar(255), start_date_time varchar(255),"
        + "end_date_time varchar(255), current_task_start_date_time varchar(255),"
        + "current_task_end_date_time varchar(255), priority float,"
        + "times_blocked int DEFAULT 0, waiting_on varchar(255) DEFAULT NULL)");
    s.execute("CREATE TABLE workflow_instance_metadata ("
        + "workflow_instance_id varchar(255), workflow_met_key varchar(255),"
        + "workflow_met_val varchar(255))");
    s.execute("SHUTDOWN");
    c.close();
  }

  public void testTheReasonOutlivesTheProcessThatWroteIt() throws Exception {
    DataSourceWorkflowInstanceRepository repo = repository();
    WorkflowInstance inst = instance();
    inst.setWaitingOn("condition:urn:drat:MapsDone");
    repo.addWorkflowInstance(inst);
    String id = inst.getId();
    repo.release();

    // A second repository over the same files is what a restart looks like.
    List<?> back = repository().getWorkflowInstances();
    WorkflowInstance found = find(back, id);
    assertNotNull("the instance did not come back", found);
    assertEquals("condition:urn:drat:MapsDone", found.getWaitingOn());
  }

  /** And an instance waiting on nothing says nothing. */
  public void testNoReasonComesBackAsNoReason() throws Exception {
    DataSourceWorkflowInstanceRepository repo = repository();
    WorkflowInstance inst = instance();
    repo.addWorkflowInstance(inst);
    String id = inst.getId();
    repo.release();

    WorkflowInstance found = find(repository().getWorkflowInstances(), id);
    assertNotNull(found);
    assertNull(found.getWaitingOn());
  }

  /** Updated in place when what it waits for changes. */
  public void testTheReasonIsUpdated() throws Exception {
    DataSourceWorkflowInstanceRepository repo = repository();
    WorkflowInstance inst = instance();
    inst.setWaitingOn("task:urn:drat:RepoCrawler");
    repo.addWorkflowInstance(inst);
    inst.setWaitingOn("condition:urn:drat:MapsSettling");
    repo.updateWorkflowInstance(inst);
    String id = inst.getId();
    repo.release();

    assertEquals("condition:urn:drat:MapsSettling",
        find(repository().getWorkflowInstances(), id).getWaitingOn());
  }

  private WorkflowInstance find(List<?> instances, String id) {
    for (Object o : instances) {
      WorkflowInstance inst = (WorkflowInstance) o;
      if (id.equals(inst.getId())) {
        return inst;
      }
    }
    return null;
  }

  private WorkflowInstance instance() {
    WorkflowInstance inst = new WorkflowInstance();
    Workflow workflow = new Workflow();
    workflow.setId("urn:oodt:w");
    WorkflowTask task = new WorkflowTask();
    task.setTaskId("urn:oodt:t");
    workflow.getTasks().add(task);
    inst.setWorkflow(workflow);
    inst.setCurrentTaskId("urn:oodt:t");
    inst.setStatus("Queued");
    inst.setSharedContext(new Metadata());
    return inst;
  }

  private DataSourceWorkflowInstanceRepository repository() {
    DataSource ds = DatabaseConnectionBuilder.buildDataSource("sa", "",
        "org.hsqldb.jdbc.JDBCDriver", url);
    return new DataSourceWorkflowInstanceRepository(ds, true, 20);
  }

  private Connection connect() throws Exception {
    Class.forName("org.hsqldb.jdbc.JDBCDriver");
    return DriverManager.getConnection(url, "sa", "");
  }
}
