/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.oodt.cas.filemgr.validation;

import static dev.hegel.Generators.lists;
import static dev.hegel.Generators.text;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import dev.hegel.Generator;
import dev.hegel.HegelTest;
import dev.hegel.TestCase;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.apache.oodt.cas.filemgr.HsqlTestDatabase;
import org.apache.oodt.cas.filemgr.structs.Element;
import org.apache.oodt.cas.filemgr.structs.ProductType;

/**
 * Properties for {@link DataSourceValidationLayer}, the database-backed policy
 * store that tells the catalog which metadata elements a product type is
 * allowed to carry.
 *
 * <p>Every statement this class runs is assembled by concatenating caller data
 * into SQL text, and the class has no unit tests, so the properties below stay
 * close to the contracts a caller depends on: an element that was added can be
 * found again, an element attached to a product type is returned for that type
 * and for no other, detaching it takes it off that type only, and a type
 * inherits its parent's elements.
 *
 * <p>Where a property needs elements to already exist it seeds them with
 * direct SQL rather than through {@code addElement}, so that a fault in the
 * write path shows up in exactly one property instead of masking every other
 * contract in the class.
 *
 * <p>The schema mirrors {@code cas-filemgr-validationlayer-schema-oracle.sql},
 * translated to HSQLDB, with the string-typed {@code product_type_id} the
 * quoting flag implies.
 */
class DataSourceValidationLayerPropertyTest {

  private static final String SCHEMA_ELEMENTS =
      "CREATE TABLE elements ("
          + "element_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,"
          + "element_name varchar(255) NOT NULL,"
          + "dc_element varchar(100),"
          + "element_description varchar(255))";

  private static final String SCHEMA_MAP =
      "CREATE TABLE product_type_element_map ("
          + "product_type_id varchar(255) NOT NULL,"
          + "element_id INTEGER NOT NULL)";

  private static final String SCHEMA_PARENTS =
      "CREATE TABLE sub_to_super_map ("
          + "product_type_id varchar(255) NOT NULL,"
          + "parent_id varchar(255) NOT NULL)";

  private static Generator<String> plainText() {
    return text().minSize(1).maxSize(8).categories("Lu", "Ll", "Nd");
  }

  private static HsqlTestDatabase freshValidationDb() throws Exception {
    HsqlTestDatabase db = HsqlTestDatabase.create("vallayer");
    try {
      db.executeAll(SCHEMA_ELEMENTS, SCHEMA_MAP, SCHEMA_PARENTS);
    } catch (Exception e) {
      db.close();
      throw e;
    }
    return db;
  }

  private static DataSourceValidationLayer layer(HsqlTestDatabase db) {
    // quoteFields=true: product_type_id values are URNs, as in every shipped policy.
    return new DataSourceValidationLayer(db.dataSource(), true);
  }

  /** Writes an element straight into the table and returns its id. */
  private static String seedElement(HsqlTestDatabase db, int id, String name) throws Exception {
    db.execute(
        "INSERT INTO elements (element_id, element_name, dc_element, element_description) "
            + "VALUES ("
            + id
            + ", '"
            + name
            + "', 'Identifier', 'seeded')");
    return String.valueOf(id);
  }

  private static ProductType type(String id) {
    ProductType type = new ProductType();
    type.setProductTypeId(id);
    type.setName(id);
    return type;
  }

  private static Element element(String id, String name) {
    Element element = new Element();
    element.setElementId(id);
    element.setElementName(name);
    element.setDCElement("Identifier");
    element.setDescription("described");
    return element;
  }

  /**
   * An element that was added must be readable back by the id the layer
   * assigned to it.
   *
   * <p>This is the only way a caller learns an element's id — {@code
   * addElement} writes it back into the object it was handed — and the id is
   * what every later call keys on.
   */
  @HegelTest(testCases = 25)
  void addedElementIsRetrievableById(TestCase tc) throws Exception {
    String name = tc.draw(plainText(), "name");
    String description = tc.draw(plainText(), "description");

    HsqlTestDatabase db = freshValidationDb();
    try {
      DataSourceValidationLayer layer = layer(db);
      Element added = element(null, name);
      added.setDescription(description);
      layer.addElement(added);

      assertNotNull(added.getElementId(), "addElement did not assign an id");
      Element back = layer.getElementById(added.getElementId());
      assertNotNull(back, "element " + added.getElementId() + " was not found by id");
      assertEquals(name, back.getElementName(), "the element name changed on the way through");
      assertEquals(description, back.getDescription(), "the description changed on the way through");
    } finally {
      db.close();
    }
  }

  /**
   * An element must be findable by the name it was stored under.
   *
   * <p>The catalog calls {@code getElementByName} on every query criterion to
   * turn the element name a user typed into the id the metadata table is keyed
   * on, so a name lookup that cannot find a stored element is a query that
   * cannot run.
   */
  @HegelTest(testCases = 25)
  void seededElementIsRetrievableByName(TestCase tc) throws Exception {
    String name = tc.draw(plainText(), "name");

    HsqlTestDatabase db = freshValidationDb();
    try {
      DataSourceValidationLayer layer = layer(db);
      String id = seedElement(db, 1, name);

      Element back = layer.getElementByName(name);
      assertNotNull(back, "element named '" + name + "' was not found by name");
      assertEquals(id, back.getElementId(), "name lookup returned the wrong element");
    } finally {
      db.close();
    }
  }

  /**
   * An element attached to a product type must be returned for that type, and
   * must not be returned for a type it was never attached to.
   *
   * <p>The catalog uses this list to decide which metadata fields it will
   * write and read for a product. An element leaking across types means one
   * type's metadata is read under another type's policy.
   */
  @HegelTest(testCases = 25)
  void elementsAreReturnedForTheirOwnProductTypeOnly(TestCase tc) throws Exception {
    List<String> mine = tc.draw(lists(plainText()).minSize(1).maxSize(4), "mine");
    List<String> theirs = tc.draw(lists(plainText()).minSize(0).maxSize(3), "theirs");

    HsqlTestDatabase db = freshValidationDb();
    try {
      DataSourceValidationLayer layer = layer(db);
      ProductType mineType = type("urn:oodt:Mine");
      ProductType theirsType = type("urn:oodt:Theirs");

      Set<String> mineIds = new LinkedHashSet<String>();
      Set<String> theirsIds = new LinkedHashSet<String>();
      int nextId = 1;

      for (String name : mine) {
        String id = seedElement(db, nextId, name + "_" + nextId);
        layer.addElementToProductType(mineType, element(id, name));
        mineIds.add(id);
        nextId++;
      }
      for (String name : theirs) {
        String id = seedElement(db, nextId, name + "_" + nextId);
        layer.addElementToProductType(theirsType, element(id, name));
        theirsIds.add(id);
        nextId++;
      }

      assertEquals(mineIds, idsOf(layer.getElements(mineType)), "wrong elements for the first type");
      assertEquals(
          theirsIds, idsOf(layer.getElements(theirsType)), "wrong elements for the second type");
    } finally {
      db.close();
    }
  }

  /**
   * Detaching an element from a product type must remove that pairing and
   * leave every other pairing alone, including the same element on another
   * type.
   */
  @HegelTest(testCases = 25)
  void detachingAnElementAffectsOnlyThatPairing(TestCase tc) throws Exception {
    List<String> names = tc.draw(lists(plainText()).minSize(2).maxSize(5), "names");

    HsqlTestDatabase db = freshValidationDb();
    try {
      DataSourceValidationLayer layer = layer(db);
      ProductType first = type("urn:oodt:First");
      ProductType second = type("urn:oodt:Second");

      List<String> ids = new ArrayList<String>();
      for (int i = 0; i < names.size(); i++) {
        String id = seedElement(db, i + 1, names.get(i) + "_" + i);
        ids.add(id);
        layer.addElementToProductType(first, element(id, names.get(i)));
      }
      // The first element is shared with a second type.
      layer.addElementToProductType(second, element(ids.get(0), names.get(0)));

      layer.removeElementFromProductType(first, element(ids.get(0), names.get(0)));

      Set<String> stillOnFirst = new LinkedHashSet<String>(ids.subList(1, ids.size()));
      assertEquals(
          stillOnFirst, idsOf(layer.getElements(first)), "detaching disturbed the other elements");
      assertEquals(
          Set.of(ids.get(0)),
          idsOf(layer.getElements(second)),
          "detaching from one type also detached from another");
    } finally {
      db.close();
    }
  }

  /**
   * A product type declared as a child of another must be given its parent's
   * elements as well as its own.
   *
   * <p>Inheritance is how shipped policies avoid restating the CAS core
   * elements on every type; a child that loses them cannot store its own
   * product name.
   */
  @HegelTest(testCases = 25)
  void childProductTypeInheritsItsParentsElements(TestCase tc) throws Exception {
    List<String> childNames = tc.draw(lists(plainText()).minSize(1).maxSize(3), "childNames");
    List<String> parentNames = tc.draw(lists(plainText()).minSize(1).maxSize(3), "parentNames");

    HsqlTestDatabase db = freshValidationDb();
    try {
      DataSourceValidationLayer layer = layer(db);
      ProductType child = type("urn:oodt:Child");
      ProductType parent = type("urn:oodt:Parent");

      Set<String> expected = new LinkedHashSet<String>();
      int nextId = 1;
      for (String name : childNames) {
        String id = seedElement(db, nextId, name + "_c" + nextId);
        layer.addElementToProductType(child, element(id, name));
        expected.add(id);
        nextId++;
      }
      for (String name : parentNames) {
        String id = seedElement(db, nextId, name + "_p" + nextId);
        layer.addElementToProductType(parent, element(id, name));
        expected.add(id);
        nextId++;
      }

      layer.addParentToProductType(child, parent.getProductTypeId());

      assertEquals(
          expected,
          idsOf(layer.getElements(child)),
          "the child did not receive its own elements plus its parent's");
    } finally {
      db.close();
    }
  }

  /**
   * {@code getElements()} with no argument must list every element in the
   * store, whether or not it is attached to any product type.
   *
   * <p>This is what the policy browser and the {@code cas-filemgr} admin tools
   * page through.
   */
  @HegelTest(testCases = 25)
  void getElementsListsEveryStoredElement(TestCase tc) throws Exception {
    List<String> names = tc.draw(lists(plainText()).minSize(0).maxSize(6), "names");

    HsqlTestDatabase db = freshValidationDb();
    try {
      DataSourceValidationLayer layer = layer(db);
      Set<String> expected = new LinkedHashSet<String>();
      for (int i = 0; i < names.size(); i++) {
        expected.add(seedElement(db, i + 1, names.get(i) + "_" + i));
      }

      List<Element> all = layer.getElements();
      assertNotNull(all, "getElements() returned null");
      assertEquals(expected, idsOf(all), "getElements() did not list exactly the stored elements");
      for (Element e : all) {
        assertTrue(e.getElementName() != null, "an element came back with no name");
      }
    } finally {
      db.close();
    }
  }

  private static Set<String> idsOf(List<Element> elements) {
    Set<String> ids = new LinkedHashSet<String>();
    if (elements != null) {
      for (Element e : elements) {
        ids.add(e.getElementId());
      }
    }
    return ids;
  }
}
